### ISSUE TITLE
A home for multilingual documentation?

### ISSUE THREAD

**Issue by ararslan** [Julia-i18n/julia-i18n#1]
I apologize that I'm not intimately familiar with the goals of this organization, but it on the surface it seems that this could be a good home for the Julia documentation/manual translated in a variety of languages. Is that currently a goal of the organization? If it is not but it is reasonably within scope, I'd like to propose that.

**Comment by Ismael-VC** [comment]
@ararslan there is no need to apologize. Indeed the goal and scope of this organization is to cover **all** things i18n in Julia! And that certainly includes the translation of the manual documentation. I'll update the README's road map.

Cheers.

**Comment by ararslan** [comment]
Great, thanks for the explanation!
